-- MySQL Script generated by MySQL Workbench
-- Tue Mar 10 13:21:15 2020
-- Model: IBMG    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ibng
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ibng` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ibng` DEFAULT CHARACTER SET utf8 ;
USE `ibng` ;

-- -----------------------------------------------------
-- Table `ibng`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ibng`.`user` ;

CREATE TABLE IF NOT EXISTS `ibng`.`user` (
  `username` VARCHAR(45) NOT NULL,
  `password_sha256` CHAR(64) NOT NULL,
  `nickname` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
